# NOTE: name is important to distinguish main and test compose configurations.
name: spring-docker-compose-demo-test

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test-mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
